Extend the client to use ESI SDK
CCI-MOC/python-esileapclient pull request #52
Opened 2024-04-26 16:54 UTC by DanNiESh

Add V2 APIs that connect to ESI SDK instead of make calls to esi-leap directly.
Related issue: https://github.com/CCI-MOC/esi/issues/474

2024-04-30 14:22 UTC, tzumainn commented
I've put an initial version of `esisdk` on pypi (https://pypi.org/project/esisdk/). Can you update `requirements.txt` here?

2024-04-30 16:10 UTC, DanNiESh commented
> I've put an initial version of `esisdk` on pypi (https://pypi.org/project/esisdk/). Can you update `requirements.txt` here?

Done!

2024-04-30 16:20 UTC, tzumainn reviewed
Quick question - is there a reason to have a v2? It would make sense to me if esi-leap had a different REST API version - then you would need both to ensure backwards compatibility - but this change really only shuffles some frontend logic around.

2024-04-30 16:47 UTC, DanNiESh commented
> Quick question - is there a reason to have a v2? It would make sense to me if esi-leap had a different REST API version - then you would need both to ensure backwards compatibility - but this change really only shuffles some frontend logic around.

Actually I was not sure when I implemented the code. I was thinking there might be a chance that we want to make calls to esi-leap directly, then we can switch to v1. But it doesn't hurt to use the sdk as the only interface for cli.

2024-04-30 22:22 UTC, tzumainn commented
> > Quick question - is there a reason to have a v2? It would make sense to me if esi-leap had a different REST API version - then you would need both to ensure backwards compatibility - but this change really only shuffles some frontend logic around.
> 
> Actually I was not sure when I implemented the code. I was thinking there might be a chance that we want to make calls to esi-leap directly, then we can switch to v1. But it doesn't hurt to use the sdk as the only interface for cli.

If that's the case, I don't see why we need two versions at all - may as well simplify the code base and only keep one.

2024-05-01 15:59 UTC, DanNiESh commented
> > > Quick question - is there a reason to have a v2? It would make sense to me if esi-leap had a different REST API version - then you would need both to ensure backwards compatibility - but this change really only shuffles some frontend logic around.
> > 
> > 
> > Actually I was not sure when I implemented the code. I was thinking there might be a chance that we want to make calls to esi-leap directly, then we can switch to v1. But it doesn't hurt to use the sdk as the only interface for cli.
> 
> If that's the case, I don't see why we need two versions at all - may as well simplify the code base and only keep one.

Okay!

2024-05-07 14:41 UTC, DanNiESh commented
I've updated the code to have v1 only.

2024-05-07 18:49 UTC, tzumainn requested changes
This looks good - however I'm seeing some strange behavior. When I run, say, `esi lease show --debug`, I get the following:

```
START with options: esi lease show ff3a59fa-4798-4831-b262-9d79f54c47e9 --debug
options: Namespace(access_token='***', access_token_endpoint='', access_token_type='', application_credential_id='', application_credential_name='', application_credential_s)
Auth plugin password selected
auth_config_hook(): {'api_timeout': None, 'verify': True, 'cacert': None, 'cert': None, 'key': None, 'baremetal_status_code_retries': '5', 'baremetal_introspection_status_co}
defaults: {'api_timeout': None, 'verify': True, 'cacert': None, 'cert': None, 'key': None, 'auth_type': 'password', 'baremetal_status_code_retries': 5, 'baremetal_introspect}
cloud cfg: {'api_timeout': None, 'verify': True, 'cacert': None, 'cert': None, 'key': None, 'baremetal_status_code_retries': '5', 'baremetal_introspection_status_code_retrie}
compute API version 2.latest, cmd group openstack.compute.v2
identity API version 3, cmd group openstack.identity.v3
/home/tzumainn/development/python-esileapclient/.venv/lib64/python3.6/site-packages/openstack/image/image_signer.py:14: CryptographyDeprecationWarning: Python 3.6 is no long.
  from cryptography.hazmat.backends import default_backend
image API version 2, cmd group openstack.image.v2
network API version 2, cmd group openstack.network.v2
object_store API version 1, cmd group openstack.object_store.v1
volume API version 3, cmd group openstack.volume.v3
lease API version 1, cmd group openstack.lease.v1
baremetal API version 1.72, cmd group openstack.baremetal.v1
command: esi lease show -> esileapclient.osc.v1.lease.ShowLease (auth=True)
Auth plugin password selected
auth_config_hook(): {'api_timeout': None, 'verify': True, 'cacert': None, 'cert': None, 'key': None, 'baremetal_status_code_retries': '5', 'baremetal_introspection_status_co}
Using auth plugin: password
Using parameters {'auth_url': 'https://esi.massopen.cloud:13000', 'project_name': 'admin', 'project_domain_name': 'Default', 'username': 'admin', 'user_domain_name': 'Defaul}
Get auth_ref
REQ: curl -g -i -X GET https://esi.massopen.cloud:13000 -H "Accept: application/json" -H "User-Agent: openstacksdk/1.2.0 keystoneauth1/5.1.2 python-requests/2.27.1 CPython/3"
Starting new HTTPS connection (1): esi.massopen.cloud:13000
https://esi.massopen.cloud:13000 "GET / HTTP/1.1" 300 275
RESP: [300] Content-Length: 275 Content-Type: application/json Date: Tue, 07 May 2024 18:40:54 GMT Location: https://esi.massopen.cloud:13000/v3/ Server: Apache Vary: X-Auth2
RESP BODY: {"versions": {"values": [{"id": "v3.14", "status": "stable", "updated": "2020-04-07T00:00:00Z", "links": [{"rel": "self", "href": "https://esi.massopen.cloud:1300}
GET call to https://esi.massopen.cloud:13000/ used request id req-5fbb1d80-6b9b-4561-abd9-fd5c0e14f8d2
Making authentication request to https://esi.massopen.cloud:13000/v3/auth/tokens
https://esi.massopen.cloud:13000 "POST /v3/auth/tokens HTTP/1.1" 201 7474
{"token": {"methods": ["password"], "user": {"domain": {"id": "default", "name": "Default"}, "id": "a2eb20a1bf94440e807c903113c71d12", "name": "admin", "password_expires_at"}
run(Namespace(columns=[], fit_width=False, formatter='table', max_width=0, noindent=False, prefix='', print_empty=False, uuid='ff3a59fa-4798-4831-b262-9d79f54c47e9', variabl)
REQ: curl -g -i -X GET http://129.10.5.142:7777 -H "Accept: application/json" -H "User-Agent: openstacksdk/1.2.0 keystoneauth1/5.1.2 python-requests/2.27.1 CPython/3.6.8"
Starting new HTTP connection (1): 129.10.5.142:7777
http://129.10.5.142:7777 "GET / HTTP/1.1" 401 114
RESP: [401] Connection: keep-alive Content-Length: 114 Content-Type: application/json Date: Tue, 07 May 2024 18:40:56 GMT Www-Authenticate: Keystone uri="https://esi.massope"
RESP BODY: {"error": {"code": 401, "title": "Unauthorized", "message": "The request you have made requires authentication."}}
Request returned failure status: 401
REQ: curl -g -i -X GET http://129.10.5.142:7777 -H "Accept: application/json" -H "User-Agent: openstacksdk/1.2.0 keystoneauth1/5.1.2 python-requests/2.27.1 CPython/3.6.8" -H"
http://129.10.5.142:7777 "GET / HTTP/1.1" 300 118
RESP: [300] Connection: keep-alive Content-Length: 118 Content-Type: application/json Date: Tue, 07 May 2024 18:40:59 GMT
RESP BODY: {"versions": [{"id": "v1.0", "status": "CURRENT", "links": [{"href": "http://129.10.5.142:7777/v1", "rel": "self"}]}]}
REQ: curl -g -i -X GET http://129.10.5.142:7777/v1/leases/ff3a59fa-4798-4831-b262-9d79f54c47e9 -H "User-Agent: openstacksdk/1.2.0 keystoneauth1/5.1.2 python-requests/2.27.1 "
http://129.10.5.142:7777 "GET /v1/leases/ff3a59fa-4798-4831-b262-9d79f54c47e9 HTTP/1.1" 200 839
RESP: [200] Connection: keep-alive Content-Length: 839 Content-Type: application/json Date: Tue, 07 May 2024 18:41:08 GMT
RESP BODY: {"name": null, "uuid": "ff3a59fa-4798-4831-b262-9d79f54c47e9", "project_id": "f9f5654ee2be438ba76538cc4f944993", "project": "storage-research", "owner_id": "ce548}
clean_up ShowLease: 
END return value: 0
```

Note the `unauthorized response` error in the middle, right after `Starting new HTTP connection`. With the current esileapclient, the same command has the following:

```
START with options: esi lease show ff3a59fa-4798-4831-b262-9d79f54c47e9 --debug
options: Namespace(access_token='***', access_token_endpoint='', access_token_type='', application_credential_id='', application_credential_name='', application_credential_secret='***', auth_methods='', auth_type='password', auth_url='https://esi.massopen.cloud:13000', cacert=None, cert='', client_id='', client_secret='***', cloud='', code='', debug=True, default_domain='default', default_domain_id='', default_domain_name='', deferred_help=False, discovery_endpoint='', domain_id='', domain_name='', endpoint='', identity_provider='', insecure=None, interface='', key='', log_file=None, oauth2_client_id='', oauth2_client_secret='***', oauth2_endpoint='', openid_scope='', os_baremetal_api_version='1.72', os_beta_command=False, os_compute_api_version='2.latest', os_dns_api_version='2', os_esiclient_api_version='1', os_identity_api_version='3', os_image_api_version='2', os_network_api_version='', os_object_api_version='', os_project_id=None, os_project_name=None, os_volume_api_version='3', passcode='', password='***', profile='', project_domain_id='', project_domain_name='Default', project_id='', project_name='admin', protocol='', redirect_uri='', region_name='regionOne', remote_project_domain_id='', remote_project_domain_name='', remote_project_id='', remote_project_name='', service_provider='', system_scope='', timing=False, token='***', trust_id='', user_domain_id='', user_domain_name='Default', user_id='', username='admin', verbose_level=3, verify=None)
Auth plugin password selected
auth_config_hook(): {'api_timeout': None, 'verify': True, 'cacert': None, 'cert': None, 'key': None, 'baremetal_status_code_retries': '5', 'baremetal_introspection_status_code_retries': '5', 'image_status_code_retries': '5', 'disable_vendor_agent': {}, 'interface': 'public', 'floating_ip_source': 'neutron', 'image_api_use_tasks': False, 'image_format': 'qcow2', 'message': '', 'network_api_version': '2', 'object_store_api_version': '1', 'secgroup_source': 'neutron', 'status': 'active', 'auth': {'user_domain_name': 'Default', 'project_domain_name': 'Default', 'project_name': 'admin'}, 'verbose_level': 3, 'deferred_help': False, 'debug': True, 'region_name': 'regionOne', 'default_domain': 'default', 'timing': False, 'auth_url': 'https://esi.massopen.cloud:13000', 'username': 'admin', 'password': '***', 'beta_command': False, 'compute_api_version': '2.latest', 'identity_api_version': '3', 'image_api_version': '2', 'volume_api_version': '3', 'baremetal_api_version': '1.72', 'esiclient_api_version': '1', 'dns_api_version': '2', 'auth_type': 'password', ': []}
defaults: {'api_timeout': None, 'verify': True, 'cacert': None, 'cert': None, 'key': None, 'auth_type' [...]

2024-05-08 17:42 UTC, DanNiESh commented
I think the reason is that esisdk attempt to discover the lease endpoint at 7777 at first. And once the endpoint is discovered, it makes calls to es-leap lease show API. I'm trying to see if we can skip the endpoint discovery step.

2024-05-09 16:16 UTC, DanNiESh commented
Updated esisdk version, this is the debug info when I ran `openstack esi offer show 0a5ed50a-5919-4036-bb7a-dc81d3eca6d4 --debug`  
```
START with options: esi offer show 0a5ed50a-5919-4036-bb7a-dc81d3eca6d4 --debug
options: Namespace(access_token='***', access_token_endpoint='', access_token_type='', application_credential_id='', application_credential_name='', application_credential_secret='***', auth_methods='', auth_type='password', auth_url='https://esi.massopen.cloud:13000', cacert=None, cert='', client_id='', client_secret='***', cloud='', code='', debug=True, default_domain='default', default_domain_id='', default_domain_name='', deferred_help=False, discovery_endpoint='', domain_id='', domain_name='', endpoint='', identity_provider='', insecure=None, interface='', key='', log_file=None, oauth2_client_id='', oauth2_client_secret='***', oauth2_endpoint='', openid_scope='', os_baremetal_api_version='1.78', os_beta_command=False, os_compute_api_version='2.latest', os_esileap_api_version='1', os_identity_api_version='3', os_image_api_version='2', os_network_api_version='', os_object_api_version='', os_project_id=None, os_project_name=None, os_volume_api_version='3', passcode='', password='***', project_domain_id='', project_domain_name='Default', project_id='', project_name='admin', protocol='', redirect_uri='', region_name='regionOne', remote_project_domain_id='', remote_project_domain_name='', remote_project_id='', remote_project_name='', service_provider='', system_scope='', timing=False, token='***', trust_id='', user_domain_id='', user_domain_name='Default', user_id='', username='admin', verbose_level=3, verify=None)
Auth plugin password selected
auth_config_hook(): {'api_timeout': None, 'verify': True, 'cacert': None, 'cert': None, 'key': None, 'baremetal_status_code_retries': '5', 'baremetal_introspection_status_code_retries': '5', 'image_status_code_retries': '5', 'disable_vendor_agent': {}, 'interface': 'public', 'floating_ip_source': 'neutron', 'image_api_use_tasks': False, 'image_format': 'qcow2', 'message': '', 'network_api_version': '2', 'object_store_api_version': '1', 'secgroup_source': 'neutron', 'status': 'active', 'auth': {'user_domain_name': 'Default', 'project_domain_name': 'Default', 'project_name': 'admin'}, 'verbose_level': 3, 'deferred_help': False, 'debug': True, 'region_name': 'regionOne', 'default_domain': 'default', 'timing': False, 'auth_url': 'https://esi.massopen.cloud:13000', 'username': 'admin', 'password': '***', 'beta_command': False, 'compute_api_version': '2.latest', 'identity_api_version': '3', 'image_api_version': '2', 'volume_api_version': '3', 'baremetal_api_version': '1.78', 'esileap_api_version': '1', 'auth_type': 'password', ': []}
defaults: {'api_timeout': None, 'verify': True, 'cacert': None, 'cert': None, 'key': None, 'auth_type': 'password', 'baremetal_status_code_retries': 5, 'baremetal_introspection_status_code_retries': 5, 'image_status_code_retries': 5, 'disable_vendor_agent': {}, 'interface': 'public', 'floating_ip_source': 'neutron', 'image_api_use_tasks': False, 'image_format': 'qcow2', 'message': '', 'network_api_version': '2', 'object_store_api_version': '1', 'secgroup_source': 'neutron', 'status': 'active'}
cloud cfg: {'api_timeout': None, 'verify': True, 'cacert': None, 'cert': None, 'key': None, 'baremetal_status_code_retries': '5', 'baremetal_introspection_status_code_retries': '5', 'image_status_code_retries': '5', 'disable_vendor_agent': {}, 'interface': 'public', 'floating_ip_source': 'neutron', 'image_api_use_tasks': False, 'image_format': 'qcow2', 'message': '', 'network_api_version': '2', 'object_store_api_version': '1', 'secgroup_source': 'neutron', 'status': 'active', 'auth': {'user_domain_name': 'Default', 'project_domain_name': 'Default', 'project_name': 'admin'}, 'verbose_level': 3, 'deferred_help': False, 'debug': True, 'region_name': 'regionOne', 'default_domain': 'default', 'timing': False, 'auth_url': 'https://esi.massopen.cloud:13000', 'username': 'admin', 'password': '***', 'beta_command': False, 'compute_api_version': '2.latest', 'identity_api_version': '3', 'image_api_version': '2', 'volume_api_version': '3', 'baremetal_api_version': '1.78', 'esileap_api_version': '1', 'auth_type': 'password', ': []}
compute API version 2.latest, cmd group openstack.compute.v2
identity API version 3, cmd group openstack.identity.v3
image API version 2, cmd group openstack.image.v2
network API version 2, cmd group openstack.network.v2
object_store API version 1, cmd group openstack.object_store.v1
volume API version 3, cmd group openstack.volume.v3
baremetal API version 1.78, cmd group openstack.baremetal.v1
lease API version 1, cmd group openstack.lease.v1
command: esi offer show -> esileapclient.osc.v1.offer.ShowOffer (auth=True)
Auth plugin password selected
auth_config_hook(): {'api_timeout': None, 'verify': True, 'cacert': None, 'cert': None, 'key': None, 'baremetal_status_code_retries': '5', 'baremetal_introspection_status_code_retries': '5', 'image_status_code_retries': '5', 'disable_vendor_agent': {}, 'interface': 'public', 'floating_ip_source': 'neutron', 'image_api_use_tasks': False, 'image_format': 'qcow2', 'message': '', 'network_api_version': '2', 'object_store_api_version': '1', 'secgroup_source': 'neutron', 'status': 'active', 'auth': {'user_domain_name': 'Default', 'project_domain_name': 'Default', 'project_name': 'admin'}, 'additional_user_agent': [('osc-lib', '2.9.0')], 'verbose_level': 3, 'deferred_help': False, 'debug': True, 'region_name': 'regionOne', 'default_domain': 'default', 'timing': False, 'auth_url': 'https://esi.massopen.cloud:13000', 'username': 'admin', 'password': '***', 'beta_command': False, 'compute_api_version': '2.latest', 'identity_api_version': '3', 'image_api_version': '2', 'volume_api_version': '3', 'baremetal_api_version': '1.78', 'esileap_api_version': '1', 'auth_type': 'password', ': []}
Using auth plugin: password
Using parameters {'auth_url': 'https://esi.massopen.cloud:13000', 'project_name': 'admin', 'project_domain_name': 'Default', 'username': 'admin', 'user_domain_name': 'Default', 'password': '***'}
Get auth_ref
REQ: curl -g -i -X GET https://esi.massopen.cloud:13000 -H "Accept: application/json" -H "User-Agent: openstacksdk/1.2.0 keystoneauth1/5.1.2 python-requests/2.31.0 CPython/3.7.17"
Starting new HTTPS connection (1): esi.massopen.cloud:13000
https://esi.massopen.cloud:13000 "GET / HTTP/1.1" 300 275
RESP: [300] Content-Length: 275 Content-Type: application/json Date: Thu, 09 May 2024 16:12:43 GMT Location: https://esi.massopen.cloud:13000/v3/ Server: Apache Vary: X-Auth-Token x-openstack-request-id: req-c7ed22b9-d421-4e49-9168-65a16e059c1b
RESP BODY: {"versions": {"values": [{"id": "v3.14", "status": "stable", "updated": "2020-04-07T00:00:00Z", "links": [{"rel": "self", "href": "https://esi.massopen.cloud:13000/v3/"}], "media-types": [{"base": "application/json", "type": "application/vnd.openstack.identity-v3+json"}]}]}}
GET call to https://esi.massopen.cloud:13000/ used request id req-c7ed22b9-d421-4e49-9168-65a16e059c1b
Making authentication request to https://esi.massopen.cloud:13000/v3/auth/tokens
https://esi.massopen.cloud:13000 "POST /v3/auth/tokens HTTP/1.1" 201 7474
{"token": {"methods": ["password"], "user": {"domain": {"id": "default", "name": "Default"}, "id": "a2eb20a1bf94440e807c903113c71d12", "name": "admin", "password_expires_at": null}, "audit_ids": ["6u26OIUMS1-I5Jte7QvDNg"], "expires_at": "2024-05-09T17:12:44.000000Z", "issued_at": "2024-05-09T16:12:44.000000Z", "project": {"domain": {"id": "default", "name": "Default"}, "id": "ce54871194264a1dafd508058c0b8614", "name": "admin"}, "is_domain": false, "roles": [{"id": "c2f2d543f1ef45d49bfd427a7d65b909", "name": "reader"}, {"id": "87bf286e240143dab8907a5d6f212707", "name": "admin"}, {"id": "82a5aebeb7c14b33b30e2cf3a1d2f2bc", "name": "member"}], "catalog": [{"endpoints": [{"id": "123ad6c4d5bb451998ff522c1f1c3758", "interface": "admin", "region_id": "regionOne",  [...]

2024-05-09 16:23 UTC, tzumainn approved these changes

2024-05-09 16:23 UTC, merged